# Generated by Django 3.1.14 on 2023-03-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Cases',
        ),
    ]
