# Generated by Django 3.1.14 on 2023-03-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230302_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='text',
        ),
        migrations.AddField(
            model_name='cases',
            name='casenumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cases',
            name='nameofparties',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cases',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
