# Generated by Django 3.1.14 on 2023-03-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20230302_0626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cases',
            new_name='Case',
        ),
    ]
