# Generated by Django 3.1.14 on 2023-03-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230302_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='casenumber',
            new_name='standard_casenumber',
        ),
    ]
