# Generated by Django 3.1.14 on 2023-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20230302_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateField(default='', max_length=100),
        ),
    ]
