# Generated by Django 3.1.14 on 2023-03-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20230302_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='Judgement',
        ),
    ]
