# Generated by Django 3.1.14 on 2023-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20230303_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgement',
            old_name='nameofparties',
            new_name='in_the_matter_of',
        ),
        migrations.AddField(
            model_name='judgement',
            name='primary_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='judgement',
            name='standard_nameofparties',
            field=models.CharField(default='', max_length=100),
        ),
    ]
