# Generated by Django 3.1.14 on 2023-03-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20230314_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement',
            name='primary_key',
            field=models.CharField(default='Unavailable', max_length=100),
        ),
    ]
