# Generated by Django 3.1.14 on 2023-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20230320_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgmentText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_key', models.CharField(default='Unavailable', max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
