# Generated by Django 3.1.14 on 2023-03-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_judgmenttext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JudgmentText',
        ),
        migrations.AddField(
            model_name='judgement',
            name='judgement_text',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
    ]
